// Code generated by gen.go. DO NOT EDIT.
// ⚠️ 本文件为服务层模板，禁止直接修改任何生成器生成的文件！
// 如需调整，请修改本模板，并通过 go run utils/gen/gen.go -table=表名 -cmd=s 等命令重新生成覆盖。

package services

import (
	"gin-go-test/app/models"
	"gorm.io/gorm"
)

// RoleService 处理Role相关的业务逻辑
type RoleService struct {
	db *gorm.DB
}

// NewRoleService 创建新的RoleService实例
func NewRoleService(db *gorm.DB) *RoleService {
	return &RoleService{db: db}
}

// GetCount 获取记录总数
func (s *RoleService) GetCount() (int64, error) {
	var count int64
	err := s.db.Model(&models.Role{}).Count(&count).Error
	return count, err
}

// List 获取记录列表
func (s *RoleService) List(page, pageSize int) ([]models.Role, error) {
	var items []models.Role
	err := s.db.Offset((page - 1) * pageSize).Limit(pageSize).Find(&items).Error
	return items, err
}

// BatchCreate 批量创建记录
func (s *RoleService) BatchCreate(items []models.Role) ([]models.Role, []error) {
	var errs []error
	var createdItems []models.Role

	for _, item := range items {
		if err := s.db.Create(&item).Error; err != nil {
			errs = append(errs, err)
		} else {
			createdItems = append(createdItems, item)
		}
	}

	return createdItems, errs
}

// BatchUpdate 批量更新记录
func (s *RoleService) BatchUpdate(items []models.Role) ([]models.Role, []error) {
	var updatedItems []models.Role
	var errs []error

	for _, item := range items {
		updateMap := make(map[string]interface{})
		if item.Id != nil {
			updateMap["id"] = *item.Id
		}
		if item.Name != nil {
			updateMap["name"] = *item.Name
		}
		if item.Desc != nil {
			updateMap["desc"] = *item.Desc
		}
		if item.DeletedAt != nil {
			updateMap["deleted_at"] = *item.DeletedAt
		}
		if len(updateMap) > 0 {
			if err := s.db.Model(&models.Role{}).Where("id = ?", *item.Id).Updates(updateMap).Error; err != nil {
				errs = append(errs, err)
				continue
			}
			var updatedItem models.Role
			if err := s.db.First(&updatedItem, *item.Id).Error; err != nil {
				errs = append(errs, err)
				continue
			}
			updatedItems = append(updatedItems, updatedItem)
		}
	}
	return updatedItems, errs
}

// BatchDelete 批量删除记录
func (s *RoleService) BatchDelete(ids []uint) []error {
	var errs []error

	for _, id := range ids {
		if err := s.db.Delete(&models.Role{}, id).Error; err != nil {
			errs = append(errs, err)
		}
	}

	return errs
}

func (s *RoleService) GetDB() *gorm.DB {
	return s.db
}

func (s *RoleService) GetDetail(id string) (*models.Role, error) {
	var item models.Role
	if err := s.db.First(&item, id).Error; err != nil {
		return nil, err
	}
	return &item, nil
}

func (s *RoleService) ListWithOrder(page, pageSize int, sort, order string) ([]*models.Role, []error) {
	var items []*models.Role
	db := s.db.Model(&models.Role{})
	if sort == "" {
		sort = "id"
	}
	if order == "" {
		order = "desc"
	}
	db = db.Order(sort + " " + order)
	err := db.Offset((page-1)*pageSize).Limit(pageSize).Find(&items).Error
	if err != nil {
		return nil, []error{err}
	}
	return items, nil
}