// Code generated by gen.go. DO NOT EDIT.
package biz

import (
	"gin-go-test/app/models"
	"gin-go-test/app/services"
)

// AdminBiz 业务逻辑层
type AdminBiz struct {
	service *services.AdminService
}

// NewAdminBiz 构造函数
func NewAdminBiz(service *services.AdminService) *AdminBiz {
	return &AdminBiz{
		service: service,
	}
}

// GetCount 获取记录总数
func (b *AdminBiz) GetCount() (int64, error) {
	return b.service.GetCount()
}

// List 获取记录列表
func (b *AdminBiz) List(page, pageSize int) ([]models.Admin, error) {
	return b.service.List(page, pageSize)
}

// BatchCreate 批量创建记录
func (b *AdminBiz) BatchCreate(items []*models.Admin) ([]models.Admin, []error) {
	// 将 []*models.Admin 转换为 []models.Admin
	modelItems := make([]models.Admin, len(items))
	for i, item := range items {
		modelItems[i] = *item
	}
	return b.service.BatchCreate(modelItems)
}

// BatchUpdate 批量更新记录
func (b *AdminBiz) BatchUpdate(items []*models.Admin) ([]models.Admin, []error) {
	// 将 []*models.Admin 转换为 []models.Admin
	modelItems := make([]models.Admin, len(items))
	for i, item := range items {
		modelItems[i] = *item
	}
	return b.service.BatchUpdate(modelItems)
}

// BatchDelete 批量删除记录
func (b *AdminBiz) BatchDelete(ids []int) []error {
	// 将 []int 转换为 []uint
	uintIds := make([]uint, len(ids))
	for i, id := range ids {
		uintIds[i] = uint(id)
	}
	return b.service.BatchDelete(uintIds)
}
