// Code generated by gen.go. DO NOT EDIT.
package biz

import (
	"gin-go-test/app/models"
	"gin-go-test/app/services"
)

// BadmintonGameBiz 处理badminton_game相关的业务逻辑
type BadmintonGameBiz struct {
	service *services.BadmintonGameService
}

// NewBadmintonGameBiz 创建新的BadmintonGameBiz实例
func NewBadmintonGameBiz(service *services.BadmintonGameService) *BadmintonGameBiz {
	return &BadmintonGameBiz{service: service}
}

// GetCount 获取记录总数
func (b *BadmintonGameBiz) GetCount() (int64, error) {
	return b.service.GetCount()
}

// List 获取记录列表
func (b *BadmintonGameBiz) List(page, pageSize int) ([]models.BadmintonGame, error) {
	return b.service.List(page, pageSize)
}

// BatchCreate 批量创建记录
func (b *BadmintonGameBiz) BatchCreate(items []*models.BadmintonGame) ([]models.BadmintonGame, []error) {
	// 将 []*models.BadmintonGame 转换为 []models.BadmintonGame
	modelItems := make([]models.BadmintonGame, len(items))
	for i, item := range items {
		modelItems[i] = *item
	}
	return b.service.BatchCreate(modelItems)
}

// BatchUpdate 批量更新记录
func (b *BadmintonGameBiz) BatchUpdate(items []*models.BadmintonGame) error {
	// 将 []*models.BadmintonGame 转换为 []models.BadmintonGame
	modelItems := make([]models.BadmintonGame, len(items))
	for i, item := range items {
		modelItems[i] = *item
	}
	return b.service.BatchUpdate(modelItems)
}

// BatchDelete 批量删除记录
func (b *BadmintonGameBiz) BatchDelete(ids []int) []error {
	// 将 []int 转换为 []uint
	uintIds := make([]uint, len(ids))
	for i, id := range ids {
		uintIds[i] = uint(id)
	}
	return b.service.BatchDelete(uintIds)
}