// Code generated by gen.go. DO NOT EDIT.
package biz

import (
	"gin-go-test/app/models"
	"gin-go-test/app/services"
)

// FileInfoBiz 处理file_info相关的业务逻辑
type FileInfoBiz struct {
	service *services.FileInfoService
}

// NewFileInfoBiz 创建新的FileInfoBiz实例
func NewFileInfoBiz(service *services.FileInfoService) *FileInfoBiz {
	return &FileInfoBiz{service: service}
}

// GetCount 获取记录总数
func (b *FileInfoBiz) GetCount() (int64, error) {
	return b.service.GetCount()
}

// List 获取记录列表
func (b *FileInfoBiz) List(page, pageSize int) ([]models.FileInfo, error) {
	return b.service.List(page, pageSize)
}

// BatchCreate 批量创建记录
func (b *FileInfoBiz) BatchCreate(items []*models.FileInfo) ([]models.FileInfo, []error) {
	// 将 []*models.FileInfo 转换为 []models.FileInfo
	modelItems := make([]models.FileInfo, len(items))
	for i, item := range items {
		modelItems[i] = *item
	}
	return b.service.BatchCreate(modelItems)
}

// BatchUpdate 批量更新记录
func (b *FileInfoBiz) BatchUpdate(items []*models.FileInfo) ([]models.FileInfo, []error) {
	// 将 []*models.FileInfo 转换为 []models.FileInfo
	modelItems := make([]models.FileInfo, len(items))
	for i, item := range items {
		modelItems[i] = *item
	}
	return b.service.BatchUpdate(modelItems)
}

// BatchDelete 批量删除记录
func (b *FileInfoBiz) BatchDelete(ids []int) []error {
	// 将 []int 转换为 []uint
	uintIds := make([]uint, len(ids))
	for i, id := range ids {
		uintIds[i] = uint(id)
	}
	return b.service.BatchDelete(uintIds)
}
