// Code generated by gen.go. DO NOT EDIT.
package biz

import (
	"gin-go-test/app/models"
	"gin-go-test/app/services"
)

// UserBiz 处理user相关的业务逻辑
type UserBiz struct {
	service *services.UserService
}

// NewUserBiz 创建新的UserBiz实例
func NewUserBiz(service *services.UserService) *UserBiz {
	return &UserBiz{service: service}
}

// GetCount 获取记录总数
func (b *UserBiz) GetCount() (int64, error) {
	return b.service.GetCount()
}

// List 获取记录列表
func (b *UserBiz) List(page, pageSize int) ([]models.User, error) {
	return b.service.List(page, pageSize)
}

// BatchCreate 批量创建记录
func (b *UserBiz) BatchCreate(items []*models.User) ([]models.User, []error) {
	// 将 []*models.User 转换为 []models.User
	modelItems := make([]models.User, len(items))
	for i, item := range items {
		modelItems[i] = *item
	}
	return b.service.BatchCreate(modelItems)
}

// BatchUpdate 批量更新记录
func (b *UserBiz) BatchUpdate(items []*models.User) ([]models.User, []error) {
	// 将 []*models.User 转换为 []models.User
	modelItems := make([]models.User, len(items))
	for i, item := range items {
		modelItems[i] = *item
	}
	return b.service.BatchUpdate(modelItems)
}

// BatchDelete 批量删除记录
func (b *UserBiz) BatchDelete(ids []int) []error {
	// 将 []int 转换为 []uint
	uintIds := make([]uint, len(ids))
	for i, id := range ids {
		uintIds[i] = uint(id)
	}
	return b.service.BatchDelete(uintIds)
}
