# 使用官方 Node 镜像作为基础
{
  "registry-mirrors": ["https://registry.docker-cn.com"]
}
FROM registry.cn-hangzhou.aliyuncs.com/aliyun-node/alinode:16

# 设置工作目录
WORKDIR /app

# 拷贝 package.json 和 package-lock.json
COPY package*.json ./

# 安装依赖
RUN npm install

# 拷贝所有源代码
COPY . .

# 暴露端口
EXPOSE 8080

# 启动 Vue 开发服务器
CMD ["npm", "run", "serve"]
