// Code generated by gen.go. DO NOT EDIT.
package controllers

import (
	"github.com/gin-gonic/gin"
	"gin-go-test/utils/generated/controller"
	"gin-go-test/app/biz"
	"gin-go-test/app/services"
	"gorm.io/gorm"
)

// RegisterExamTemplateRoutes 注册 ExamTemplate 相关路由
func RegisterExamTemplateRoutes(router *gin.Engine, db *gorm.DB) {
	group := router.Group("/api/exam_template")
	skeleton := controller.NewExamTemplateSkeleton(biz.NewExamTemplateBiz(services.NewExamTemplateService(db)))
	group.GET("/count", skeleton.CountHandler)
	group.GET("/list", skeleton.ListHandler)
	group.POST("", skeleton.BatchCreateHandler)
	group.PUT("", skeleton.BatchUpdateHandler)
	group.DELETE("", skeleton.BatchDeleteHandler)
}