// Code generated by gen.go. DO NOT EDIT.
package controllers

import (
	"github.com/gin-gonic/gin"
	"gin-go-test/utils/generated/controller"
	"gin-go-test/app/biz"
	"gin-go-test/app/services"
	"gorm.io/gorm"
)

// RegisterExamPapersRoutes 注册 ExamPapers 相关路由
func RegisterExamPapersRoutes(router *gin.Engine, db *gorm.DB) {
	group := router.Group("/api/exam_papers")
	skeleton := controller.NewExamPapersSkeleton(biz.NewExamPapersBiz(services.NewExamPapersService(db)))
	group.GET("/count", skeleton.CountHandler)
	group.GET("/list", skeleton.ListHandler)
	group.POST("", skeleton.BatchCreateHandler)
	group.PUT("", skeleton.BatchUpdateHandler)
	group.DELETE("", skeleton.BatchDeleteHandler)
}