// Code generated by gen.go. DO NOT EDIT.
package controllers

import (
	"gin-go-test/app/biz"
	"gin-go-test/app/services"
	"gin-go-test/utils/generated/controller"
	"github.com/gin-gonic/gin"
	"gorm.io/gorm"
)

// RegisterFileInfoRoutes 注册 FileInfo 相关路由
func RegisterFileInfoRoutes(router *gin.Engine, db *gorm.DB) {
	group := router.Group("/api/file_info")
	skeleton := controller.NewFileInfoSkeleton(biz.NewFileInfoBiz(services.NewFileInfoService(db)))
	group.GET("/count", skeleton.CountHandler)
	group.GET("/list", skeleton.ListHandler)
	group.POST("", skeleton.BatchCreateHandler)
	group.PUT("", skeleton.BatchUpdateHandler)
	group.DELETE("", skeleton.BatchDeleteHandler)
}
