// Code generated by gen.go. DO NOT EDIT.
package controllers

import (
	"github.com/gin-gonic/gin"
	"gin-go-test/utils/generated/controller"
	"gin-go-test/app/biz"
	"gin-go-test/app/services"
	"gorm.io/gorm"
)

// RegisterMd=roleRoutes 注册 Md=role 相关路由
func RegisterMd=roleRoutes(router *gin.Engine, db *gorm.DB) {
	group := router.Group("/api/md=role")
	skeleton := controller.NewMd=roleSkeleton(biz.NewMd=roleBiz(services.NewMd=roleService(db)))
	group.GET("/count", skeleton.CountHandler)
	group.GET("/list", skeleton.ListHandler)
	group.POST("", skeleton.BatchCreateHandler)
	group.PUT("", skeleton.BatchUpdateHandler)
	group.DELETE("", skeleton.BatchDeleteHandler)
}