// Code generated by gen.go. DO NOT EDIT.
package controllers

import (
	"github.com/gin-gonic/gin"
	"gin-go-test/utils/generated/controller"
	"gin-go-test/app/biz"
	"gin-go-test/app/services"
	"gorm.io/gorm"
)

// RegisterTeacherRoutes 注册 Teacher 相关路由
func RegisterTeacherRoutes(router *gin.Engine, db *gorm.DB) {
	group := router.Group("/api/teacher")
	skeleton := controller.NewTeacherSkeleton(biz.NewTeacherBiz(services.NewTeacherService(db)))
	group.GET("/count", skeleton.CountHandler)
	group.GET("/list", skeleton.ListHandler)
	group.POST("", skeleton.BatchCreateHandler)
	group.PUT("", skeleton.BatchUpdateHandler)
	group.DELETE("", skeleton.BatchDeleteHandler)
}