// Code generated by gen.go. DO NOT EDIT.
package controllers

import (
	"github.com/gin-gonic/gin"
	"gin-go-test/utils/generated/controller"
	"gin-go-test/app/biz"
	"gin-go-test/app/services"
	"gorm.io/gorm"
)

// RegisterTmExamTemplateRoutes 注册 TmExamTemplate 相关路由
func RegisterTmExamTemplateRoutes(router *gin.Engine, db *gorm.DB) {
	group := router.Group("/api/tm_exam_template")
	skeleton := controller.NewTmExamTemplateSkeleton(biz.NewTmExamTemplateBiz(services.NewTmExamTemplateService(db)))
	group.GET("/count", skeleton.CountHandler)
	group.GET("/list", skeleton.ListHandler)
	group.POST("", skeleton.BatchCreateHandler)
	group.PUT("", skeleton.BatchUpdateHandler)
	group.DELETE("", skeleton.BatchDeleteHandler)
}