// Code generated by gen.go. DO NOT EDIT.
package controllers

import (
	"gin-go-test/app/biz"
	"gin-go-test/app/services"
	"gin-go-test/utils/generated/controller"
	"github.com/gin-gonic/gin"
	"gorm.io/gorm"
)

// RegisterUserRoutes 注册 User 相关路由
func RegisterUserRoutes(router *gin.Engine, db *gorm.DB) {
	group := router.Group("/api/user")
	skeleton := controller.NewUserSkeleton(biz.NewUserBiz(services.NewUserService(db)))
	group.GET("/count", skeleton.CountHandler)
	group.GET("/list", skeleton.ListHandler)
	group.POST("", skeleton.BatchCreateHandler)
	group.PUT("", skeleton.BatchUpdateHandler)
	group.DELETE("", skeleton.BatchDeleteHandler)
}
